language: java
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key: ee6fd3e9-5166-4037-a0a7-c3bf881f2fe6
  app: frozen-ravine-27172
  on:
    repo: samusfc/hello-java
