language: java
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: jN0FoixqeGV6wtBS2HG7Lc5HP8ggKlGJ1sNxNmPlPR26oBWOnd0BDN+GRJnIsHW8OTHyxreqxR/0fV6uAzTRj12vq40VNmQ3dLj7Bo9R0bdn5klsBBaX28WACG8dcuhHotETxCLJ/kY/vtqpSjQcEwBsLsQ1LEM6thZEx2Lgqlt8IHP9oLB7YTJRb140LG3fcTGIg8HWT46ciOFP1J72pEDnDxPn3NmjHAFKCk5uJiuRBL0hP6O9k9zvIUvBGyTxuZFRkGoDUtLbSVF/uaee7x9Yq+o2neE8KXIQ3RfPF779jSfNFIuqtBXI7JrWjZzBsSIlBxPXRfeo+q7i/mGWK/bViWzGfDtEfJFGgB6QpjE1NNVltrViWsFt0pEt2v+xBPu9tGiBbQbQeCH5+hWbkGcOevhcaqtLZRESX12cAW5WkIJu2b9ix9fEMKGO0EAcXqJzzwU9oTlDfPJWoMC5Zt9XEHhuOQ3IAZht0opv/EK9hRrnsLlXEsLFNRn78ihtwAUhr8d2ULsbFwFgUlx6dPo1WVf6IYRw8qSFouZXkLqZITMeL6uV2bDGac0DE5TYtnHxgVOL4bMr+pz7fqI+mDSCDwJnRjmS10LUx3tYSIsJk1x+PANeUs5vzjEH3u70PbfJQmjLTbSx2VFzn2A4JkyLba85MAlLhDG7aFU1/y4=
  app: frozen-ravine-27172
  on:
    repo: samusfc/hello-java
